<?php


use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;


function first_form_theme($existing, $type, $theme, $path) {

  return [
    'student_details_template' => [
      'render element' => 'form',
      'template' => 'student-details-template',
    ],
  ];
}

function first_form_form_node_student_details_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  // Add submit handler to store data in custom table.
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'first_form_store_student_details_submit';
    }
  }
  $form['actions']['submit']['#value'] = t('Save Student Details');
}

function first_form_store_student_details_submit(&$form, FormStateInterface &$form_state) {

  // Get the submitted values from $form_state.
  $values = $form_state->getValues();
 //print "<pre>"; print_r($values);  print "</pre>"; exit;
  // Collect the values which needs to store in custom table.
  $details['rollno'] = $values['field_roll_no'][0]['value'];
  $details['name'] = $values['field_name'][0]['value'];
  $details['email'] = $values['field_email1'][0]['value'];
  $details['dob'] = strtotime($values['field_date_of_birth1'][0]['value']);
  $details['gender'] = $values['field_gender'][0]['value'];
  $details['standard'] = $values['field_standard'][0]['value'];
  
  $connection = Database::getConnection();
    $connection ->insert('student')->fields(
      [
         'rollno' => $details['rollno'],
         'name' => $details['name'],
         'email' => $details['email'],
         'dob' => $details['dob'],
         'gender' => $details['gender'],
         'standard' => $details['standard'],
      ]
        )->execute();

  /*Drupal::service('first_form.student_details')->StoreStudentDetails($details);*/

  drupal_set_message('Student Details has been stored successfully in custom table.');
}

function getData($id) {
return \Drupal::database()->select('student _details', 'n')
           ->fields('n', array('id', 'rollno', 'name', 'email', 'dob' , 'gender' , 'standard'))
           ->condition('n.id', $id)
           ->execute()->fetchAll();

}

